apiVersion: apps/${BUILD_NUMBER}
kind: Deployment
metadata:
  name: test-app
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: test
        image: angurajnagaraj/python-app-sample:33
        ports:
        - containerPort: 8000
